OLED_ENABLE = yes
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
# ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes
# RGBLIGHT_ENABLE = no
# VIALRGB_ENABLE = yes
RGB_MATRIX_ENABLE = yes
QMK_SETTINGS = no
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
CAPS_WORD_ENABLE = yes
LAYER_LOCK_ENABLE = yes
REPEAT_KEY_ENABLE = no
WPM_ENABLE = yes

# "lighting": "vialrgb", add to vial json if VIALRGB_ENABLE is enabled


